#!/bin/csh
#
# make-synplify
# - run:  tdfc -xc ...
#         tdfc -synplify      ...
#         tdfc -synplify -pp1 ...
# - Eylon Caspi, 9/30/04

################################################################

set tdfc = (../../../tdfc -DAPPROX_DIV -DMODULO_COUNTER)

set qi = (-qim Q_lwpipe -qid 16 -qil 0 -qiw 1)
set ql = (-qlm Q_lwpipe -qld 16 -qll 0 -qlw 0)	# ignored
set qo = (-qom Q_lwpipe -qod 16 -qol 1 -qow 1)

set tdfxcsrcs = ()

set tdfsrcs   = (pipe.tdf)

################################################################

# command line option "-n" prevents cmd execution, print only
set execute = 1
if ($#argv > 0) then
  if ($argv[1] == "-n") then
    set execute = 0
  else
    echo "Usage:  $0 [-n]"
    exit
  endif
endif

foreach tdfxcsrc ($tdfxcsrcs)
  set cmd = ($tdfc -xc $tdfxcsrc > ${tdfxcsrc}.xc)
  echo $cmd
  if ($execute) eval $cmd
end

set cmd = ($tdfc -synplify      $qi $ql $qo $tdfsrcs)
echo $cmd
if ($execute) eval $cmd

set cmd = ($tdfc -synplify -pp1 $qi $ql $qo $tdfsrcs)
echo $cmd
if ($execute) eval $cmd
