#!/bin/csh

# - Create xilinx build directories for all "_ior.v" register shells
#     * except:  page queues, segments, top/appl. "dpq"
#                (but include top/appl. queues)
#     * including expanded area builds for "<appl>_ior.v"
# - Call this inside an application directory, after "verilog-reg-shells"
# - Usage:  XILINX-DIRS [xilinx-dirs-63i options]
#           (options applied to all modules except "<appl>_ior.v")
# - Eylon Caspi, 9/30/04 3/1/05

if (-d V) then
  echo "oops, directory V already exists"
  exit
endif

set appl = (`ls -1 *_noin.v | egrep -v '^_page_' | perl -npe 's{_noin\.v}{}'`)

mkdir V

# - Application
mv *.v V
mv V/${appl}_ior.v .
~/brass/tdfc/tools/xilinx-dirs-63i 1.0 1.1 1.2 1.3 1.4 1.5 2.0 unconstrained
mv V/* .

# - Page tops only
mv *.v V
mv V/_page_*_ior.v .
mv   _page_*_q_ior.v _page_*_qin_ior.v _page_*_noin_ior.v _page_*_dpq_ior.v V
~/brass/tdfc/tools/xilinx-dirs-63i $*
mv V/* .

rmdir V
