#all:	vectorAddTest.o
tdfc_rot.cpp tdfc_rot.cuh tdfc_rot.cc:	tdfc_rot.tdf
	/home/cody/Internship/tdfc/tdfc -ecuda tdfc_rot.tdf


#vectorAddTest.o:	vectorAddTest.cpp tdfc_vadd.tdf tdfc_vadd.cc 	/home/cody/Internship/tdfc/tdfc  /home/cody/Internship/ScoreRuntime/libScoreRuntime.a
#	/home/cody/Internship/tdfc/tdfc -ecc  tdfc_vadd.tdf
	
#	g++ -Wno-write-strings -I/opt/leda/incl -I/home/cody/Internship/ScoreRuntime   -L/home/cody/Internship/ScoreRuntime -L/opt/leda   vectorAddTest.cpp  tdfc_vadd.cc -o vectorAddTest.o -lScoreRuntime -lleda -lX11 -lpthread
