all:	addtest.o
addtest.o:	addtest.cpp add.tdf /opt/tdfc/tdfc  /opt/ScoreRuntime/libScoreRuntime.a
	/opt/tdfc/tdfc -ecc add.tdf
	g++ -Wno-write-strings -I/opt/leda/incl -I/opt/ScoreRuntime   -L/opt/ScoreRuntime -L/opt/leda   addtest.cpp add.cc -o addtest.o -lScoreRuntime -lleda -lX11 -lpthread
