all:	addtest.o
addtest.o:	addtest.cpp add.tdf add.cc 	/home/abid/PhD/HighLevelSynthesis/Compiler/tdfc  /home/abid/PhD/HighLevelSynthesis/ScoreRuntime/libScoreRuntime.a
	/home/abid/PhD/HighLevelSynthesis/Compiler/tdfc -edfgcc add.tdf
	g++ -Wno-write-strings -I/opt/leda/incl -I/home/abid/PhD/HighLevelSynthesis/ScoreRuntime   -L/home/abid/PhD/HighLevelSynthesis/ScoreRuntime -L/opt/leda   addtest.cpp add.cc -o addtest.o -lScoreRuntime -lleda -lX11 -lpthread
