#!/bin/csh
#
# concatenate every synplify result file:  everilog-*L*W*/*/proj/*.xls
# with each line preceded by <logic depth> <wire depth> <app>

# proj = "proj" for synplify, "proj-xilinx" for xilinx
set proj = "proj"
set xls  = "synplify-pp1+dpq-summary3-rev4.xls"

set nonomatch
set dirs = (`find . -mindepth 1 -maxdepth 1 -type d -name everilog-\*L\*W\*`)

echo "Logic Pipe	Wire Pipe	Application	TDF Name	Component	Module	Revision	Clock (MHz)	LUTs	FFs	LUT-FFs	States	FSM Style	"

foreach dir ($dirs)
  set l = (`echo $dir | perl -ne '/L(\d+)W(\d+)$/; print $1'`)
  set w = (`echo $dir | perl -ne '/L(\d+)W(\d+)$/; print $2'`)
  pushd $dir >&/dev/null
  foreach app (`cat APPS`)
#   set      xls_file = ($app/$proj/*.xls)
    set      xls_file = ($app/$proj/$xls)
    if ( -f $xls_file ) then
#     echo   xls_file = $xls_file
      perl -ne 'if ($i++ >= 4) { print "'$l'\t'$w'\t'$app'\t$_" }'  $xls_file
    endif
  end
  popd >& /dev/null
end
