#!/bin/csh
# Print qstat results to prevent tty connections from closing

set sleepseconds=60

while (1)
  set running=`qmine-running`
  set mine=`qmine`
  if ($mine <= 10)  qstat -u $USER
  echo `date` / $running running / $mine mine
  sleep $sleepseconds
end
