#!/usr/sww/bin/perl
#
#  retrieves largest revision number (major.minor) among all RCS files
#
#  Eylon Caspi 6/14/99

$rcs_dirs = "RCS/*,v */RCS/*,v";

$r1  = 0;	# major revision num.
$r2  = 0;	# minor revision num.
open(RLOG,"rlog $rcs_dirs|") || die "could not launch RCS rlog";
while (<RLOG>)
{
    if (/^revision (\d+)\.(\d+)/ && ($1>$r1 || $2>$r2))
    {
	$r1=$1;
	$r2=$2
    }
}
print "Latest revision in ($rcs_dirs) is:  $r1.$r2\n";
