#!/bin/csh
# - Distill synthesis results from Synplify 7 .srr file -- CLOCK SPEED (MHZ)
# - $speed

	  perl -e							\
	    'while (<>) {						\
	       if (/(clock|system) +(\d+(.\d+)?) +MHz +(\d+(.\d)?)/i)	\
	         { if ($speed==0 || $speed>$4) { $speed=$4; } }		\
	     }								\
	     print "$speed\n" '						\
	     $*
