#!/usr/bin/perl
# - Distill synthesis results from Synplify 7 .srr file -- CLOCK PERIOD (NS)
# - $period

while (<>) {
  if (/(clock|system) +(\d+(.\d+)?) +MHz +(\d+(.\d)?)/i)
    { if ($speed==0 || $speed>$4) { $speed=$4; } }
}
$period = ($speed==0) ? "" : (1000./$speed);
print "$period\n";
