#!/bin/csh
#
# Synplify the given behavioral module families (top, FSM, DP)
#   in this directory, every implementation / revision thereof
#
# Usage:  synplify-family family ...
#
# Assume separate project directories for top, FSM, DP modules,
#            each project directory named after its module
#   - top is named "<topmodule>"
#   - FSM is named "<topmodule>_fsm"
#   - DP  is named "<topmodule>_dp"
#
# Synplify 7.1
# Eylon Caspi, 5/8/03

set toolpath = ${0:h}

if ($#argv<1) then
  echo Usage:  synplify-family family ...
  exit
endif

set topmodules = ($argv[*])

foreach topmodule ($topmodules)
  foreach revpath ($topmodule/rev*)
    set rev = ${revpath:t}
    $toolpath/synplify-impl $topmodule $rev
  end
end
