#!/bin/csh
#
# Compile a given "-pp1" page module family (top/page, noin, op, fsm, dp),
#   in this directory, every implementation / revision thereof,
#   from EDIF to Xilinx Virtex II,
# Separately compile the page composition, behavioral op, but NOT queues
#
# Usage:  xilinx-pp1-family family ...
#
# Assume separate project directories for top/page, noin, queue modules,
#            each project directory named after its module
#   - top (i.e. page)     is named "<topmodule>"
#   - input queue         is named "<topmodule>_qin"   (ignored)
#   - output/local queue  is named "<topmodule>_q"     (ignored)
#   - ops w/o input queue is named "<topmodule>_noin"
#
# Note, tdfc -pp1 names compositional top module "_page_<basemodule>"
#
# Xilinx ISE 5.2i
# Eylon Caspi, 10/16/03

set toolpath = ${0:h}

if ($#argv<1) then
  echo Usage:  xilinx-pages-family family ...
  exit
endif

set topmodules = ($argv[*])

foreach topmodule ($topmodules)
  # - page composition:
  foreach revpath ($topmodule/rev*)
    set rev = ${revpath:t}
    $toolpath/xilinx-pages-impl $topmodule $rev omit_queues
  end
  # - operator in page:
  set  basemodule = ${topmodule:s/_page_//}
  if ($basemodule != $topmodule) then
    foreach revpath ($basemodule/rev*)
      set rev = ${revpath:t}
      $toolpath/xilinx-impl $basemodule $rev
    end
  endif
end
