//////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 1999 The Regents of the University of California 
// Permission to use, copy, modify, and distribute this software and
// its documentation for any purpose, without fee, and without a
// written agreement is hereby granted, provided that the above copyright 
// notice and this paragraph and the following two paragraphs appear in
// all copies. 
//
// IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
// DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING
// LOST PROFITS, ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
// EVEN IF THE UNIVERSITY OF CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF
// SUCH DAMAGE. 
//
// THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
// INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
// AND FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON
// AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATIONS TO
// PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS. 
//
//////////////////////////////////////////////////////////////////////////////
//
// BRASS source file
//
// SCORE TDF compiler:  types for generated C++ output
// $Revision: 1.130 $
//
//////////////////////////////////////////////////////////////////////////////


#define TYPE_BOOLEAN_SCORE_STREAM        "BOOLEAN_SCORE_STREAM"
#define TYPE_SIGNED_SCORE_STREAM         "SIGNED_SCORE_STREAM"
#define TYPE_UNSIGNED_SCORE_STREAM       "UNSIGNED_SCORE_STREAM"
#define TYPE_SIGNED_FIXED_SCORE_STREAM   "SIGNED_FIXED_STREAM"
#define TYPE_UNSIGNED_FIXED_SCORE_STREAM "UNSIGNED_FIXED_STREAM"
#define TYPE_SCORE_STREAM                "SCORE_STREAM"

#define TYPE_SCORE_SEGMENT_RANDOM_READ           "ScoreSegmentReadOnly"
#define TYPE_SCORE_SEGMENT_RANDOM_WRITE          "ScoreSegmentWriteOnly"
#define TYPE_SCORE_SEGMENT_RANDOM_READ_WRITE     "ScoreSegmentReadWrite"
#define TYPE_SCORE_SEGMENT_SEQUENTIAL_READ       "ScoreSegmentSeqReadOnly"
#define TYPE_SCORE_SEGMENT_SEQUENTIAL_WRITE      "ScoreSegmentSeqWriteOnly"
#define TYPE_SCORE_SEGMENT_SEQUENTIAL_READ_WRITE "ScoreSegmentSeqReadWrite"

#define TYPE_SCORE_SEGMENT_OPERATOR_RANDOM_READ           "ScoreSegmentOperatorReadOnly"
#define TYPE_SCORE_SEGMENT_OPERATOR_RANDOM_WRITE          "ScoreSegmentOperatorWriteOnly"
#define TYPE_SCORE_SEGMENT_OPERATOR_RANDOM_READ_WRITE     "ScoreSegmentOperatorReadWrite"
#define TYPE_SCORE_SEGMENT_OPERATOR_SEQUENTIAL_READ       "ScoreSegmentOperatorSeqReadOnly"
#define TYPE_SCORE_SEGMENT_OPERATOR_SEQUENTIAL_WRITE      "ScoreSegmentOperatorSeqWriteOnly"
#define TYPE_SCORE_SEGMENT_OPERATOR_SEQUENTIAL_READ_WRITE "ScoreSegmentOperatorSeqReadWrite"

// TODO: change definition to distinct types
#define TYPE_SCORE_SEGMENT                "SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_UNSIGNED       "UNSIGNED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_SIGNED         "SIGNED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_UNSIGNED_FIXED "UNSIGNED_FIXED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_SIGNED_FIXED   "SIGNED_FIXED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_BOOLEAN        "BOOLEAN_SCORE_SEGMENT"

#define TYPE_BOOLEAN_SCORE_STREAM_CONSTRUCTOR  "NEW_BOOLEAN_SCORE_STREAM"
#define TYPE_SIGNED_SCORE_STREAM_CONSTRUCTOR   "NEW_SIGNED_SCORE_STREAM"
#define TYPE_UNSIGNED_SCORE_STREAM_CONSTRUCTOR "NEW_UNSIGNED_SCORE_STREAM"
#define TYPE_SIGNED_FIXED_STREAM_CONSTRUCTOR   "NEW_SIGNED_FIXED_STREAM"
#define TYPE_UNSIGNED_FIXED_STREAM_CONSTRUCTOR "NEW_UNSIGNED_FIXED_STREAM"

#define TYPE_BOOLEAN_SCORE_STREAM_CONSTRUCTOR        "NEW_BOOLEAN_SCORE_STREAM"
#define TYPE_SIGNED_SCORE_STREAM_CONSTRUCTOR         "NEW_SIGNED_SCORE_STREAM"
#define TYPE_UNSIGNED_SCORE_STREAM_CONSTRUCTOR       "NEW_UNSIGNED_SCORE_STREAM"
#define TYPE_SIGNED_FIXED_SCORE_STREAM_CONSTRUCTOR   "NEW_SIGNED_FIXED_SCORE_STREAM"
#define TYPE_UNSIGNED_FIXED_SCORE_STREAM_CONSTRUCTOR "NEW_UNSIGNED_FIXED_SCORE_STREAM"

// stream constructor suffixes:
#define TYPE_DEPTH_HINT_SUFFIX "_DEPTH_HINT"
#define TYPE_PAGESTEP_SUFFIX   "_ARRAY"


// TODO: change definition to distinct types
#define TYPE_SCORE_SEGMENT_CONSTRUCTOR                "NEW_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_UNSIGNED_CONSTRUCTOR       "NEW_UNSIGNED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_SIGNED_CONSTRUCTOR         "NEW_SIGNED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_UNSIGNED_FIXED_CONSTRUCTOR "NEW_UNSIGNED_FIXED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_SIGNED_FIXED_CONSTRUCTOR   "NEW_SIGNED_FIXED_SCORE_SEGMENT"
#define TYPE_SCORE_SEGMENT_BOOLEAN_CONSTRUCTOR        "NEW_BOOLEAN_SCORE_SEGMENT"

#define TYPE_STREAM_ID_CONVERT   "STREAM_OBJ_TO_ID"
#define TYPE_SEGMENT_ID_CONVERT  "SEGMENT_OBJ_TO_ID"
#define TYPE_STREAM_OBJ_CONVERT  "STREAM_ID_TO_OBJ"
#define TYPE_SEGMENT_OBJ_CONVERT "SEGMENT_ID_TO_OBJ"

