#!/bin/csh
#
# make-synplify
# - run:  tdfc -xc ...
#         tdfc -synplify      ...
#         tdfc -synplify -pp1 ...
# - Eylon Caspi, 9/30/04 3/1/05

################################################################

set tdfc = (../../../tdfc -DAPPROX_DIV -DMODULO_COUNTER)

set qi = (-qim Q_srl_reserve_nolwpipe -qid 16 -qili 0 -qiw 0)
set ql = (-qlm Q_srl_reserve_lwpipe   -qld 16 -qlli 0 -qlw 0)
set qo = (-qom Q_lwpipe               -qod 16 -qoli 0 -qow 0)

set syntech   = (-syntech VIRTEX2P-XC2VP70-FF1704-7)

set tdfxcsrcs = (repeatTar.tdf)

set tdfsrcs   = (topAll.tdf muxToSegY.tdf muxToSegC.tdf modeModule.tdf pattDetect.tdf DCTab.tdf HuffMachine.tdf IModule.tdf ISub.tdf MZLE.tdf MixToHuff.tdf PModule.tdf Passthru.tdf adjust.tdf breakup.tdf choose8.tdf chromAdd.tdf error_cmp.tdf fllm.tdf motTrunc.tdf motion.tdf muxCodeRef.tdf muxReforEst.tdf muxtoDCT.tdf muxToP.tdf muxToI.tdf pmode.tdf prepeat2.tdf proc_end.tdf repeat_motion.tdf segRefManage.tdf seg_manage.tdf segcBank.tdf segc_manage.tdf segrepC.tdf segrepY.tdf segyBank.tdf segyMref.tdf splitter.tdf sumi.tdf switchoff8.tdf switchoff8s.tdf tpose.tdf unify.tdf unifyc.tdf zigzag_.tdf distribute.tdf mquant.tdf    repeatTar.tdf.xc)

################################################################

# command line option "-n" prevents cmd execution, print only
set execute = 1
if ($#argv > 0) then
  if ($argv[1] == "-n") then
    set execute = 0
  else
    echo "Usage:  $0 [-n]"
    exit
  endif
endif

foreach tdfxcsrc ($tdfxcsrcs)
  set cmd = ($tdfc -xc $tdfxcsrc > ${tdfxcsrc}.xc)
  echo $cmd
  if ($execute) eval $cmd
end

# set cmd = ($tdfc      -synplify $syntech $qi $ql $qo $tdfsrcs)
# echo $cmd
# if ($execute) eval $cmd

set cmd = ($tdfc -pp1 -synplify $syntech $qi $ql $qo $tdfsrcs)
echo $cmd
if ($execute) eval $cmd
